language: go
go:
  - 1.14.x
  - tip
  - master
env:
  - GO111MODULE=on
install:
  - go get -v golang.org/x/lint/golint
script:
  - golint -set_exit_status ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip